export default {
  globalAxiosOptions: {
    baseURL: process.env.VUE_APP_BASE_URL
  },
  api: [{
    name: '通用查询接口',
    method: 'queryData',
    url: '/api/v1/basic/queryData'
  }, {
    name: '通用查询分页接口',
    method: 'pagingData',
    url: '/api/v1/basic/pagingData'
  }, {
    name: '通用新增接口',
    method: 'add',
    url: '/api/v1/basic/execute',
    type: 'post'
  }, {
    name: '通用删除接口',
    method: 'remove',
    url: '/api/v1/basic/execute',
    type: 'delete'
  }, {
    name: '通用修改接口',
    method: 'modify',
    url: '/api/v1/basic/execute',
    type: 'put'
  }, {
    name: '用户登录',
    method: 'login',
    url: '/api/v1/user/login',
    type: 'post'
  }, {
    name: '菜单接口',
    method: 'menu',
    url: '/api/v1/menu'
  }, {
    name: '批量插入',
    method: 'batchInsertOrgIssues',
    url: '/insertOrgIssue',
    type: 'post'
  }, {
    name: '批量插入',
    method: 'batchInsertMustInvoice',
    url: '/batchInsertMustInvoice',
    type: 'post'
  }, {
    name: '批量插入',
    method: 'batchInsertReformDetail',
    url: '/batchInsertReformDetail',
    type: 'post'
  }, {
    name: '批量插入',
    method: 'batchInsertCollectData',
    url: '/batchInsertCollectData',
    type: 'post'
  }, {
    name: '批量插入',
    method: 'batchInsertCheckAccess',
    url: '/batchInsertCheckAccess',
    type: 'post'
  }, {
    name: '删除改革历程',
    method: 'deleteDevCourse',
    url: '/deleteDevCourse',
    type: 'get'
  }, {
    name: '批量插入',
    method: 'batchInsertReformImplement',
    url: '/batchInsertReformImplement',
    type: 'post'
  }, {
    name: '批量插入',
    method: 'batchInsertMedicalReform',
    url: '/batchInsertMedicalReform',
    type: 'post'
  }, {
    name: '批量插入',
    method: 'batchInsertOnlineAgen',
    url: '/batchInsertOnlineAgen',
    type: 'post'
  }, {
    name: '批量插入',
    method: 'batchInsertMedicalChange',
    url: '/batchInsertMedicalChange',
    type: 'post'
  }, {
    name: '批量插入',
    method: 'batchInsertMedicalBooked',
    url: '/batchInsertMedicalBooked',
    type: 'post'
  }
  ]
}
